amqp:
  host: ${AMQP_RABBIT_HOST}
  port: ${AMQP_RABBIT_PORT}
  username: ${AMQP_RABBIT_USERNAME}
  password: ${AMQP_RABBIT_PASSWORD}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

resource-server:
  issuer-uri: ${RESOURCE_SERVER_ISSUER_URI}