redis:
  host: localhost
  port: 6880

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    url: jdbc:h2:mem:ecommerce-users;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true
    locations: classpath:db/dev/migration