aws-cloud:
  access-key: 123
  secret-key: 456
  s3:
    bucketName: testeBucket
    region: us-east-1

amqp:
  admin:
    auto-create: true
  host: localhost
  port: 5555
  username: ecommerce_users_admin
  password: ecommerce_users_admin123456

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    url: jdbc:h2:mem:ecommerce-users;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true
    locations: classpath:db/dev/migration