logging:
  level:
    root: DEBUG

server:
  undertow:
    threads:
      worker: 10
      io: 2

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poc-oauth2?useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/dev/migration