version: '3.7'

services:
  rabbitmq:
    container_name: ecommerce-users-rabbitmq
    image: rabbitmq:3.8.3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG1312213
      - RABBITMQ_DEFAULT_USER=ecommerce_users_admin
      - RABBITMQ_DEFAULT_PASS=ecommerce_users_admin123456
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - ecommerce_users_network

networks:
  ecommerce_users_network: