name: CI - Run tests after push

on:
  push:
    branches:
      - feature/*
      - refactor/*
      - hotfix/*
      - bugfix/*
      - release/*
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Run application tests
        run: ./gradlew test --rerun-tasks
